# Generated by Django 5.2 on 2025-08-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
